/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es.rfgr.cr4vegas;

import es.rfgr.cr4vegas.controlador.Consumer;
import es.rfgr.cr4vegas.controlador.ControladorCR4VegasInyector;
import es.rfgr.cr4vegas.controlador.ControladorCR4VegasInyectorImp;
import es.rfgr.cr4vegas.modelo.ModeloCR4Vegas;
import es.rfgr.cr4vegas.modelo.postgresql.ModeloCR4VegasImp;
import es.rfgr.cr4vegas.modelo.postgresql.exceptions.DAOException;
import es.rfgr.cr4vegas.vista.VistaCR4Vegas;
import es.rfgr.cr4vegas.vista.VistaCR4VegasImp;
import es.rfgr.cr4vegas.vista.modelo.VistaModelo;
import es.rfgr.cr4vegas.vista.modelo.imp.ModeloPrincipalImp;
import es.rfgr.cr4vegas.vista.modelo.imp.ModeloVentanaImp;
import es.rfgr.cr4vegas.vista.modelo.imp.VistaModeloImp;

public class MainApp_IUGrafica_PostgreSQL {

	public static void main(String[] args) {

		try {
			ModeloCR4Vegas modelo = new ModeloCR4VegasImp();
			VistaCR4Vegas vista = new VistaCR4VegasImp();
			VistaModelo vistaModelo = new VistaModeloImp(new ModeloPrincipalImp(), new ModeloVentanaImp());

			ControladorCR4VegasInyector inyector = new ControladorCR4VegasInyectorImp(modelo, vista, vistaModelo);
			Consumer app = inyector.getConsumer();

			app.comenzar();

		} catch (DAOException e) {
			e.printStackTrace();
		}
	}
}
